AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  ElasticsearchDomain: 
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      DomainName: "aws-rekognition-sample"
      ElasticsearchClusterConfig: 
        InstanceCount: "1"
        InstanceType: "t2.medium.elasticsearch"
        ZoneAwarenessEnabled: "false"
      EBSOptions: 
        EBSEnabled: "true"
        VolumeSize: 35
        VolumeType: "gp2"
      SnapshotOptions: 
        AutomatedSnapshotStartHour: "0"
      AccessPolicies: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS: "arn:aws:iam::292765368090:root"
            Action: "es:*"
            Resource: "arn:aws:es:us-west-1:292765368090:domain/aws-rekognition-sample/*"
      AdvancedOptions: 
        rest.action.multi.allow_explicit_index: "true"